# Generated by Django 5.1.2 on 2024-12-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_quiz_numquestions_questions_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='answer',
        ),
        migrations.AddField(
            model_name='options',
            name='answer',
            field=models.IntegerField(default=1),
        ),
    ]
