# Generated by Django 5.1.2 on 2024-12-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_remove_questions_answer_options_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='answer',
            field=models.CharField(default='', max_length=200),
        ),
    ]
