# Generated by Django 5.1.2 on 2024-12-20 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_options_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='options',
            old_name='questions',
            new_name='question',
        ),
    ]
