# Generated by Django 5.1.2 on 2024-12-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_rename_questions_options_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='options',
            name='answer',
        ),
        migrations.AddField(
            model_name='questions',
            name='answer',
            field=models.CharField(default='', max_length=200),
        ),
    ]
