# Generated by Django 5.1.2 on 2024-12-23 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_alter_userquizdata_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquizdata',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz'),
        ),
        migrations.DeleteModel(
            name='quiztime',
        ),
    ]
