# Generated by Django 5.1.2 on 2024-12-23 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_userquizdata_quiz_delete_quiztime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquizdata',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz'),
        ),
    ]
